jdi-testing/jdi-dark

.travis.yml, reports.sh
[#10](https://github.com/jdi-testing/jdi-dark/issues/10) - Create CI pipeline in travis.com
=> add travis file

jdi-dark-bdd-tests/src/test/resources/features/GetAndPost.feature, jdi-dark-bdd-tests/src/test/resources/features/JsonResponse.feature, jdi-dark-bdd/src/main/java/com/epam/jdi/http/stepdefs/en/RequestStepsEN.java, jdi-dark/src/main/java/com/epam/http/requests/RestMethod.java
Fixed 3 bdd tests:
- GetAndPost.feature
- JsonResponse.feature
- RequestHeaders.feature
Note: Separate task #41 is created for fixing Headers issues that causes LoadService.feature failure.
=> Bdd tests fixes

jdi-dark/src/main/java/com/epam/http/requests/RestMethod.java
+ Fixed similar issues for query params, cookies.
=> Fixed issue with duplicated headers in requests.

jdi-dark-tests/src/test/java/com/epam/jdi/httptests/ErrorMessageTrelloTest.java
ErrorMessageTrelloTest class is added for error handling cases for TrelloAPI
=> 45 error message test

.gitignore, .travis.yml, jdi-dark-tests/pom.xml, jdi-dark-tests/src/test/resources/general.xml, reports.sh
Add http tests to travis build
=> Travis tests

jdi-dark/pom.xml
=> add log4j dependency

jdi-dark-tests/src/main/java/com/epam/jdi/httptests/JettyService.java, jdi-dark-tests/src/test/java/com/epam/jdi/httptests/DeleteTest.java
DeleteTest class similar to rest assured is added
=> 55 delete test

jdi-dark-bdd-tests/src/main/java/com/epam/jdi/httptests/ServiceExample.java, jdi-dark-bdd-tests/src/test/java/com/epam/jdi/httptests/steps/InitService.java, jdi-dark-bdd/src/main/java/com/epam/jdi/http/stepdefs/en/RequestStepsEN.java, jdi-dark-tests/src/main/java/com/epam/jdi/httptests/ServiceExample.java, jdi-dark-tests/src/main/java/com/epam/jdi/httptests/TrelloApi.java, jdi-dark-tests/src/test/java/com/epam/jdi/httptests/TrelloTests.java, jdi-dark/src/main/java/com/epam/http/annotations/Method.java, jdi-dark/src/main/java/com/epam/http/requests/ServiceInit.java
expand imports like .*;
remove unused imports
need to announcement and initiate variable "service"
jdi-dark-bdd-tests package
InitService class
jdi-dark-bdd package
RequestStepsEN class
=> expand .* imports 

jdi-dark/src/main/java/com/epam/http/requests/RestMethod.java, jdi-dark/src/main/java/com/epam/http/requests/RestRequest.java
[#74](https://github.com/jdi-testing/jdi-dark/issues/74) - improve custom logger
=> Remove rest-assured logs. Add more info to custom logger.

jdi-dark-tests/pom.xml, jdi-dark-tests/src/main/java/com/epam/jdi/httptests/PostmanAuth.java, jdi-dark-tests/src/main/java/com/epam/jdi/httptests/PostmanInfo.java, jdi-dark-tests/src/test/java/com/epam/jdi/httptests/PostmanAuthTests.java
Authentication tests with postman examples.
=> Authentication tests with postman examples.

jdi-dark-tests/src/test/java/com/epam/jdi/httptests/PostmanAuthTests.java, jdi-dark-tests/src/test/java/com/epam/jdi/httptests/ServiceTest.java, jdi-dark/src/main/java/com/epam/http/requests/RequestData.java, jdi-dark/src/main/java/com/epam/http/requests/RestMethod.java, jdi-dark/src/main/java/com/epam/http/requests/ServiceInit.java
Add ability send predifined RestSpecification to init service метод
Add ability ignore predefined settings during specification cleaning
Rename getSpec method to addRestSpecificationData
Add example of using to ServiceTest class
=> Preliminary restassured settings

jdi-dark-tests/src/main/java/com/epam/jdi/httptests/JettyService.java, jdi-dark-tests/src/test/java/com/epam/jdi/httptests/AdvancedValidationTest.java
AdvancedValidationTest class similar to rest assured is added
=> 50 advanced validation test

jdi-dark-tests/pom.xml, jdi-dark-tests/src/test/java/com/epam/jdi/httptests/BodyWithCustomContentTypeTest.java, jdi-dark-tests/src/test/java/com/epam/jdi/httptests/DeleteTest.java, jdi-dark-tests/src/test/java/com/epam/jdi/httptests/HeaderTests.java, jdi-dark-tests/src/test/java/com/epam/jdi/httptests/JSONPostTests.java, jdi-dark-tests/src/test/java/com/epam/jdi/httptests/ObjectMappingTests.java, jdi-dark-tests/src/test/java/com/epam/jdi/httptests/ResponseTests.java, jdi-dark-tests/src/test/resources/general.xml, jdi-dark-tests/src/test/resources/jetty-logging.properties, jdi-dark/pom.xml, jdi-dark/src/main/java/com/epam/http/requests/RestMethod.java, jdi-dark/src/main/java/com/epam/http/requests/ServiceInit.java
use local jetty service for tests
add all tests to testng suit
=> #88 fix run multiple classes

jdi-dark-bdd/src/main/java/com/epam/jdi/http/stepdefs/en/ServiceStepsEN.java, jdi-dark-tests/src/main/java/com/epam/jdi/httptests/SimpleService.java, jdi-dark/src/main/java/com/epam/http/requests/RestMethods.java
Update files regarding Travis attention points 
jdi-dark-bdd/src/main/java/com/epam/jdi/http/stepdefs/en/ServiceStepsEN.java
remove: Line 7 import static com.epam.jdi.http.Utils.*;
jdi-dark-tests/src/main/java/com/epam/jdi/httptests/SimpleService.java
remove: line 3: import com.epam.http.annotations.*;
jdi-dark/src/main/java/com/epam/http/requests/RestMethods.java
remove: line 5: import static com.epam.http.requests.RestMethodTypes.*;
=> Task 18 revision 2

jdi-dark-tests/src/main/java/com/epam/jdi/httptests/JettyService.java, jdi-dark-tests/src/test/java/com/epam/jdi/httptests/AdvancedValidationTest.java, jdi-dark-tests/src/test/java/com/epam/jdi/httptests/ParamTest.java, jdi-dark-tests/src/test/resources/general.xml
ParamTest class similar to rest assured is added.
In addition, using local jetty service is added for ParamTest and AdvancedValidation test.
ParamTest and AdvancedValidation tests are added to testng suit
=> 74 param test

jdi-dark-tests/src/main/java/com/epam/jdi/httptests/JettyService.java, jdi-dark-tests/src/test/java/com/epam/jdi/httptests/ContentTypeTests.java
=> 49 create content type tests

jdi-dark-tests/src/main/java/com/epam/jdi/httptests/JettyService.java, jdi-dark-tests/src/main/java/com/epam/jdi/httptests/TrelloApi.java, jdi-dark/src/main/java/com/epam/http/requests/RestMethods.java
[#97](https://github.com/jdi-testing/jdi-dark/issues/97) - one file ignored, two files improved.
=> Fix codacy settings.

jdi-dark-bdd-tests/src/test/resources/test.properties, jdi-dark-tests/src/test/resources/test.properties, jdi-dark/src/main/java/com/epam/http/JdiHttpSettigns.java, jdi-dark/src/main/java/com/epam/http/logger/HTTPLogger.java, jdi-dark/src/main/java/com/epam/http/logger/ILogger.java, jdi-dark/src/main/java/com/epam/http/logger/LogLevels.java
[#96](https://github.com/jdi-testing/jdi-dark/issues/96) Add ability to put setting values in .properties file.
=> Custom logger from jdi and loading settings from .properties file.

jdi-dark-tests/src/main/java/com/epam/jdi/httptests/ServiceExample.java, jdi-dark-tests/src/test/java/com/epam/jdi/httptests/PostmanAuthTests.java, jdi-dark-tests/src/test/java/com/epam/jdi/httptests/ServiceTest.java, jdi-dark/src/main/java/com/epam/http/requests/RequestData.java, jdi-dark/src/main/java/com/epam/http/requests/RestMethod.java, jdi-dark/src/main/java/com/epam/http/requests/ServiceInit.java, jdi-dark/src/main/java/com/epam/http/requests/components/JDIHeaders.java, jdi-dark/src/main/java/com/epam/http/response/RestResponse.java
-Move work with headers to JDIHeafers class
-Update tests
-Add example using of method instead of field in ServiceExample
=> Add class for headers

jdi-dark-tests/src/test/resources/test.properties, jdi-dark/src/main/java/com/epam/http/JdiHttpSettigns.java, jdi-dark/src/main/java/com/epam/http/requests/ServiceInit.java
[#129](https://github.com/jdi-testing/jdi-dark/issues/129) - Add domain parameter to .properties.
=> Added doman parameter to .properties and to ServiceInit.

jdi-dark-tests/src/main/java/com/epam/jdi/httptests/JettyService.java, jdi-dark-tests/src/test/java/com/epam/jdi/httptests/PathParamTests.java, jdi-dark-tests/src/test/resources/general.xml, jdi-dark/src/main/java/com/epam/http/requests/RestMethod.java
https://github.com/jdi-testing/jdi-dark/issues/115
https://github.com/jdi-testing/jdi-dark/issues/52
=> 52 path test added

jdi-dark-tests/src/main/java/com/epam/jdi/httptests/JettyService.java, jdi-dark-tests/src/test/java/com/epam/jdi/httptests/HeaderTests.java
More header tests are implemented
=> Header tests

jdi-dark-tests/src/test/java/com/epam/jdi/httptests/ConfigITest.java
=> ConfigTests

.travis.yml
=> Remove bdd tests from travis build.

jdi-dark-tests/src/test/java/com/epam/jdi/httptests/HeaderTests.java, jdi-dark/src/main/java/com/epam/http/requests/components/JDIHeaders.java
Fixed: multivalue string[][] parsing, javadoc typos;
test examples added
=> Fixes for 128_HeadersRework

jdi-dark-tests/src/main/java/com/epam/jdi/httptests/JettyService.java, jdi-dark-tests/src/test/java/com/epam/jdi/httptests/ParamTest.java, jdi-dark/src/main/java/com/epam/http/annotations/FormParameter.java, jdi-dark/src/main/java/com/epam/http/annotations/FormParameters.java, jdi-dark/src/main/java/com/epam/http/requests/RequestData.java, jdi-dark/src/main/java/com/epam/http/requests/RestMethod.java, jdi-dark/src/main/java/com/epam/http/requests/ServiceInit.java
#137 Implemented form params ability.
=> Implemented form params ability.

jdi-dark-tests/src/test/java/com/epam/jdi/httptests/HeaderTests.java
Small fixes to follow new principles in framework
=> Fixed header tests for consistency

jdi-dark-tests/src/main/java/com/epam/jdi/httptests/TrelloApi.java, jdi-dark/src/main/java/com/epam/http/requests/ServiceInit.java
[#129](https://github.com/jdi-testing/jdi-dark/issues/129) - fix variable pattern
=> Change properties variable pattern.

jdi-dark-tests/src/test/java/com/epam/jdi/httptests/ErrorMessageTrelloTest.java, jdi-dark-tests/src/test/java/com/epam/jdi/httptests/PostmanAuthTests.java
fix PostmanAuthTests.authBaseFailTest and ErrorMessageTreloTest.deleteNotExistsCardFromBoard
=> fix failed cases

jdi-dark-tests/src/test/resources/local.properties, jdi-dark-tests/src/test/resources/test.properties, jdi-dark/src/main/java/com/epam/http/logger/AllureLogger.java, jdi-dark/src/main/java/com/epam/http/requests/RestMethod.java, jdi-dark/src/main/java/com/epam/http/requests/ServiceInit.java, jdi-dark/src/main/java/com/epam/http/response/RestResponse.java
Fix duplications in allure report.
=> Fix duplications in allure report.

jdi-dark-tests/src/main/java/com/epam/jdi/httptests/JettyService.java, jdi-dark-tests/src/test/java/com/epam/jdi/httptests/ParamTest.java
=> 124_ParamTest

jdi-dark-tests/src/main/java/com/epam/jdi/httptests/JettyService.java, jdi-dark-tests/src/test/java/com/epam/jdi/httptests/HeaderTests.java
Service Object methods for headers are implemented
=> 171_HeadersTestsUsingSOMethods

jdi-dark-tests/pom.xml, jdi-dark-tests/src/test/java/com/epam/jdi/httptests/TestsWithPreconditions.java, jdi-dark-tests/src/test/resources/general.xml, jdi-dark-tests/src/test/resources/testWithPreconditions.csv
=> Issue130-Add examples to use precondition requestData

jdi-dark-tests/src/main/java/com/epam/jdi/httptests/JettyService.java, jdi-dark-tests/src/test/java/com/epam/jdi/httptests/JSONPostTests.java, jdi-dark/src/main/java/com/epam/http/requests/RequestData.java
JSONPostTests were updated according to the last framework's changes
requestFormParams methods were added to RequestData (similar to query and path params)
=> 111 post tests

jdi-dark-tests/pom.xml, jdi-dark-tests/src/main/java/com/epam/jdi/httptests/JettyService.java, jdi-dark-tests/src/test/java/com/epam/jdi/httptests/ProxyTest.java, jdi-dark/src/main/java/com/epam/http/annotations/Proxy.java, jdi-dark/src/main/java/com/epam/http/requests/RequestData.java, jdi-dark/src/main/java/com/epam/http/requests/RestMethod.java, jdi-dark/src/main/java/com/epam/http/requests/ServiceInit.java
proxy support was added to service objects
=> 178 add proxy to service objects

jdi-dark-tests/src/main/java/com/epam/jdi/httptests/JettyService.java, jdi-dark-tests/src/test/java/com/epam/jdi/httptests/PathParamTests.java
Path params initialization was encapsulated in the service methods
=> 218 improving pathParamsTests

jdi-dark-bdd-tests/src/test/java/CucumberTestRunner.java
update: CucumberTestRunner.java
add package name;
=> add package name;

jdi-dark-tests/src/test/java/com/epam/jdi/httptests/PerformanceTests.java, jdi-dark/src/main/java/com/epam/http/performance/PerformanceResult.java
Rename method name 'NoFails' according [a-z][a-zA-Z0-9]
=> rename The method name

jdi-dark-bdd/src/main/java/com/epam/jdi/http/stepdefs/en/ResponseStepsEN.java, jdi-dark-tests/pom.xml, jdi-dark-tests/src/test/java/com/epam/jdi/httptests/AuthenticationTests.java, jdi-dark-tests/src/test/java/com/epam/jdi/httptests/CookiesTests.java, jdi-dark-tests/src/test/java/com/epam/jdi/httptests/CustomAuthenticationTests.java, jdi-dark-tests/src/test/java/com/epam/jdi/httptests/DeleteTest.java, jdi-dark-tests/src/test/java/com/epam/jdi/httptests/ErrorMessageTrelloTest.java, jdi-dark-tests/src/test/java/com/epam/jdi/httptests/JSONPostTests.java, jdi-dark-tests/src/test/java/com/epam/jdi/httptests/PostmanAuthTests.java, jdi-dark-tests/src/test/java/com/epam/jdi/httptests/ResponseTests.java, jdi-dark-tests/src/test/java/com/epam/jdi/httptests/ServiceTest.java, jdi-dark/src/main/java/com/epam/http/performance/PerformanceResult.java, jdi-dark/src/main/java/com/epam/http/requests/RestMethod.java, jdi-dark/src/main/java/com/epam/http/response/RestResponse.java
public -> private + (get / set)ers
update String Comparison
=> Codacy Task20 update 3-11-2020 2:56am (wanna sleep  see you today a bit later)I  will atempt to fix issues regaring status has private access

jdi-dark-tests/src/test/java/com/epam/jdi/httptests/examples/customsettings/AuthenticationTests.java
Fixed javadoc issues in headers tests
=> Fixed javadoc issues in headers tests

jdi-dark-tests/src/test/java/com/epam/jdi/httptests/examples/requestparams/negativeTests.java
add verification response status 400
=> negative test status 400 & special characterss in request

jdi-dark/pom.xml, jdi-dark/src/main/java/com/epam/http/requests/RequestData.java
=> using lombok for request data

CHANGELOG.md, README.md, jdi-dark-bdd-tests/pom.xml, jdi-dark-tests/src/test/java/com/epam/jdi/httptests/examples/customsettings/LoggingCustomizeTests.java, jdi-dark/src/main/java/com/epam/http/requests/RestMethod.java, jdi-dark/src/main/java/com/epam/http/response/RestResponse.java
=> 370 reset log

jdi-dark-tests/src/main/java/com/epam/jdi/dto/GreetingItself.java, jdi-dark-tests/src/main/java/com/epam/jdi/dto/User.java, jdi-dark-tests/src/main/java/com/epam/jdi/services/JettyService.java, jdi-dark-tests/src/test/java/com/epam/jdi/httptests/examples/custom/DataMethodTests.java
Added Java class with a few tests.
=> DataMethodTests class added

jdi-dark-rest-service/src/main/java/com/epam/jdi/bookstore/model/Book.java, jdi-dark-rest-service/src/main/java/com/epam/jdi/bookstore/model/Genre.java, jdi-dark-rest-service/src/main/java/com/epam/jdi/bookstore/model/user/Address.java, jdi-dark-rest-service/src/main/java/com/epam/jdi/bookstore/model/user/Role.java, jdi-dark-rest-service/src/main/java/com/epam/jdi/bookstore/service/GenreService.java, jdi-dark-rest-service/src/main/java/com/epam/jdi/bookstore/service/impl/BooksServiceImpl.java, jdi-dark-rest-service/src/main/java/com/epam/jdi/bookstore/service/impl/GenreServiceImpl.java, jdi-dark-rest-service/src/test/java/com/epam/jdi/bookstore/restassured/bookapi/CreateBookTests.java, jdi-dark-rest-service/src/test/java/com/epam/jdi/bookstore/restassured/bookapi/GetBookTests.java, jdi-dark-rest-service/src/test/java/com/epam/jdi/bookstore/restassured/bookapi/UpdateBookTests.java
Additional validation, schema and bug fixes
=> Rest service update

jdi-dark-ws/src/main/java/com/epam/jdi/http/WebSocketGenericEndpoint.java
Add missed method that clears queue.
=> WebSocket module hotfix

jdi-dark-bdd-tests/pom.xml, jdi-dark-bdd/pom.xml, jdi-dark-rest-service/pom.xml, jdi-dark-tests/pom.xml, jdi-dark-ws/pom.xml, jdi-dark/pom.xml, pom.xml
Release plugin is added.
We can use this command to update all versions
`mvn release:update-versions -DautoVersionSubmodules`
=> Change version to 1.1.9-SNAPSHOT

jdi-dark-tests/pom.xml, jdi-dark/src/main/java/com/epam/http/logger/AllureLogger.java
Replaced deprecated methods calls
=> Fix methods calls for latest Allure versions

jdi-dark-tests/src/test/java/com/epam/jdi/httptests/examples/soap/YandexSpellerSOAPTests.java
=> Disable Yandex speller tests
